### ISSUE TITLE
Add a parameter (of type bool) to NextGenSeqUtils.matchPrimer() function which indicates whether we do or do not know primer pairs

### ISSUE THREAD

**Issue by dnk8n** [MurrellGroup/NextGenSeqUtils.jl#11]
Just noticed comment:

#THIS PRIMER MATCHING FUNCTION DOESN'T ASSUME WE KNOW PRIMER PAIRS

which explains the unexpected behaviour I was experiencing.

It would be very useful to be able to pass an additional argument to the function which indicates we know the primer pairs. This would require fwd and rev barcode arrays to be of same length. 

This would avoid invalid pairings that are possible otherwise.

**Comment by dnk8n** [comment]
Seems straight forward to implement. I will wait for comment before proceeding though.

**Comment by murrellb** [comment]
Invalid pairings usually indicate an issue with the wetlab prep; primer contamination, picking the wrong tube, a mislabelling somewhere, or maybe just a miscommunication to the analyst. So I'd argue that they should always be reported, and the user can explicitly ignore or re-assign those pairs, but they shouldn't just be dropped.

In any case, don't pay too much attention to the demux stuff in this version, because we've just re-written it completely.

**Comment by dnk8n** [comment]
Fair point. I agree with that view actually.

The match score would in any case be bad in the case where my initial proposal was accepted, so better to have the extra knowledge as to why many of the scores were so bad.

In our pipeline, this is the only function we use. Will the externals of this function be changed drastically?

**Comment by dnk8n** [comment]
Just noticed branch, primerTrimming. Is that the branch you are referring to? Not too much breaking changes so far, just some additional output to consider (and some optional input, `epsilon = 2, trim = false`)

**Comment by murrellb** [comment]
There are now two demux ecosystems. The completely rebuilt one is "demux_dict()", which is extremely fast. But maybe hold off on all of this stuff for a bit?

**Comment by dnk8n** [comment]
Yes. I am not working on this anymore. We just faced invalid pairings for the first time, so I just handled new file outputs in the format `"unknown_$(pool_name)_$(invalid_primer_pair)"`

We should close this issue I think, as it is not relevant. But thank you so much for the feedback.

**Comment by murrellb** [comment]
Great! Let me know when you figure out what caused the spurious pairings!
