### ISSUE TITLE
filtering by expected error rather than average Q-score

### ISSUE THREAD

**Issue by ColinAnthony** [MurrellGroup/NextGenSeqUtils.jl#9]
This is a feature request

Filtering sequences by average Q-score has potential issues (as per the links)
https://www.drive5.com/usearch/manual/avgq.html
https://www.drive5.com/usearch/manual/exp_errs.html

Would it be possible to add the option to filter PacBio raw data by expected errors, rather than average Q-score?

**Comment by murrellb** [comment]
This is what we already do.
